### ISSUE TITLE
Update to build with semigroups 0.18

### ISSUE THREAD

**Issue by runeksvendsen** [MedeaMelana/JsonGrammar2#12]
Hi

First of all, thank you for creating this library. I had been writing JSON instances by hand for a while, always feeling like I was doing redundant work, so I'm really glad I've found this.

When I try to build my project using the Stack lts-5.2 snapshot, I get the following error:

```
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      semigroups: needed (>=0.5 && <0.17), 0.18.1 found (latest applicable is 0.16.2.2)
      stack-prism: needed (>=0.1 && <0.2), couldn't resolve its dependencies
    needed for package: JsonGrammar-1.0.3

--  Failure when adding dependencies:    
      profunctors: needed (>=4.0 && <5.2), 5.2 found (latest applicable is 5.1.2)
    needed for package: stack-prism-0.1.4

```

Would it be possible to update `JsonGrammar` and `stack-prism` to work with the newer versions `semigroups` and `profunctors`, respectively?

**Comment by MedeaMelana** [comment]
Thanks for your interest and the bug report Rune! All done, please cabal update and try again. :-)

**Comment by runeksvendsen** [comment]
Wow! That was fast. Thank you sir!
