### ISSUE TITLE
Consider using lens prisms instead of Piso

### ISSUE THREAD

**Issue by MedeaMelana** [MedeaMelana/JsonGrammar2#3]
Instead of depending on package Piso for partial isomorphisms, we should explore the option of depending on lenses, specifically prisms, for wrapping and unwrapping constructors.

Right now there is function `fromPiso` that converts a `Piso` to a `Grammar` (specifically a `Pure` node); perhaps we can write a function `fromPrism` that converts a prism to a `Pure` node.

**Comment by edsko** [comment]
This is done, no?

**Comment by MedeaMelana** [comment]
Yes! Thanks for reminding me
